### PR TITLE
adds opt out of monthly email reports checkbox to profile

### LINKED ISSUE #1142: Ability to opt out of monthly email reports
# Feature Request

Users should be able to opt out of receiving monthly emails about article downloads

## Describe the solution you'd like

On the profile page, there should be a checkbox for controlling this. Something like this:

__Email Settings__:
- [ ] Receive monthly report on downloads and views

### PR DESCRIPTION
**Pull request by banukutlu**
Closes #1142

### CODE REVIEW

**Comment by nicktiberi** [comment]
I tested this locally and it works, but I am a little confused on the wording + the name of the field.

The name of the field is `opt_out_stats_email`, which to me, implies that if that value is true (the checkbox is checked), the user is opting out and does not want to receive the monthly email.

However, the text is `Receive monthly report on downloads and views`, which implies that if the checkbox is checked, they are actually opting in, and want to receive the monthly email.

So maybe this should actually be inverted, and that checking the box should set `opt_out_stats_email` to `false`, and unchecking it should set it to `true`. Or maybe to be less confusing, we should change the name of the field to `receive_stats_email` to better align with the help text.

We also may need to invert the check in `user.rake` depending on how we proceed with this: https://github.com/psu-libraries/scholarsphere/blob/develop/lib/tasks/user.rake#L8

What do you think?

**Comment by banukutlu** [comment]
> I tested this locally and it works, but I am a little confused on the wording + the name of the field.
> 
> The name of the field is `opt_out_stats_email`, which to me, implies that if that value is true (the checkbox is checked), the user is opting out and does not want to receive the monthly email.
> 
> However, the text is `Receive monthly report on downloads and views`, which implies that if the checkbox is checked, they are actually opting in, and want to receive the monthly email.
> 
> So maybe this should actually be inverted, and that checking the box should set `opt_out_stats_email` to `false`, and unchecking it should set it to `true`. Or maybe to be less confusing, we should change the name of the field to `receive_stats_email` to better align with the help text.
> 
> We also may need to invert the check in `user.rake` depending on how we proceed with this: https://github.com/psu-libraries/scholarsphere/blob/develop/lib/tasks/user.rake#L8
> 
> What do you think?

Oh you are right, I will invert the checkbox value. Changing the field name would need a migration and it is used in couple place, I think it is easier to just invert the value.

**Comment by banukutlu** [comment]
@nicktiberi I ended up just changing the language of the checkbox rather than reversing the logic, seemed cleaner this way.

**Review by nicktiberi — APPROVED** [review]
😎

**Pull request merged**
