### PR TITLE
Add vim to Dockerfile

### PR DESCRIPTION
**Pull request by awead**
I've found that I needed to edit some files in the container.

### CODE REVIEW

**Comment by whereismyjetpack** [comment]
This is kind of an anti pattern, any file that is edited in the container will be reverted on the next container restart, leaving the application in an undesirable state. If I understood the usecase a bit I might be able to come up with a more stable solution

**Comment by awead** [comment]
I'm going off of what I saw in the catalog Dockefile. I've needed to use a editor in the deployed container before but there hasn't been one.

**Comment by awead** [comment]
It's been for debugging or doing some one-off work, so I wouldn't expect the changes to persist between deployments.

**Comment by whereismyjetpack** [comment]
Oof that was a mistake.

**Pull request closed without merging**
