### PR TITLE
Autocomplete work metadata from RMD data

### LINKED ISSUE #1462: OA Article Pathway: RMD Connection
# Feature Request
Ideally, metadata fields that RMD has information for could be autofilled. 

- [ ] Send request for metadata based on DOI and/or title search (may need to leave this option to a future development time depending on difficulty)
- [ ] Auto-fill metadata fields and disable editing of DOI and Title

### PR DESCRIPTION
**Pull request by ajkiessl**
fixes #1462 

There's a lot going on in the backend, but from the user perspective it's just a form to input a valid DOI.  Submitting this uses that DOI to find the work RMD and autocomplete a handful of data.  It basically creates a draft of the work for the user to complete or fix anything that needs completed or fixed.
Screenshot 2024-03-26 at 4 10 29 PM

The help text will need updated.

### CODE REVIEW

**Review by Smullz622 — DISMISSED** [review]
LGTM!

**Comment by ajkiessl** [comment]
@Smullz622 Doesn't have to be today, but when you get some time could you review this?  Hoping to get this deployed this week.

**Comment by Smullz622** [comment]
My bad, thought I had but guess it didn't go through

**Review by Smullz622 — APPROVED** [review]
lgtm!

**Pull request merged**
