### PR TITLE
UI for withdraw work versions

### LINKED ISSUE #1154: UI for admins to withdraw versions
# Feature Request

The work settings page should include an admin-only UI for withdrawing work versions.

## Describe the solution you'd like

The UI could be as simple as a drop down listing versions (v1, v2, ...) and a button to withdraw. It should be possible to withdraw any published version.

## What does "done" look like?

On the work settings page, there is a section only visible to admins for withdrawing a version. The UI is a drop-down list of currently published versions and button to "withdraw".

### PR DESCRIPTION
**Pull request by banukutlu**
Closes #1154 

Screen Shot 2022-01-19 at 3 52 17 PM

### CODE REVIEW

**Comment by banukutlu** [comment]
@srerickson If you give me a better explanation text to display under the Withdraw a Version heading, I will update that.

**Review by rschenk — DISMISSED** [review]
Looks good to me, but I might be biased 😃

**Review by nicktiberi — DISMISSED** [review]
This is awesome! I tested it out locally and it works great 👍

**Comment by srerickson** [comment]
This looks great! I will work on language. I believe the following is true: "Withdrawing the only published version of a work will remove this work from public search results." Is this right based on your understanding of the code?

**Comment by banukutlu** [comment]
> This looks great! I will work on language. I believe the following is true: "Withdrawing the only published version of a work will remove this work from public search results." Is this right based on your understanding of the code?

Seth, I believe that is true, I also tested on my local.

**Review by nicktiberi — APPROVED** [review]
🚀

**Pull request merged**
