### PR TITLE
citation doi hotfix

### PR DESCRIPTION
**Pull request by Smullz622**
doi was not displaying because it was pulling from work version instead of work

### CODE REVIEW

**Review by whereismyjetpack — APPROVED** [review]

**Comment by whereismyjetpack** [comment]
I'm ok merging this with CI failures. my previous PR should fix this up for main

**Comment by ajkiessl** [comment]
@Smullz622 Would there ever be an instance where the `identifier` field in WorkVersion has the DOI, but the minted DOI in Work is not present?

**Comment by Smullz622** [comment]
@ajkiessl I think overall yes, but not for datasets (which is what this is confined to). My understanding is that they will only have a minted doi since they are only published through scholarsphere

**Comment by whereismyjetpack** [comment]
If the database isn't requiring a field, we should probably prefer safe navigation _just in case_

**Comment by ajkiessl** [comment]
I think `#blank?` handles nils

**Review by ajkiessl — APPROVED** [review]

**Comment by whereismyjetpack** [comment]
i think you're right. nevermind!

**Pull request merged**
